// <auto-generated />
using System;
using DiscountCodeGeneratorService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscountCodeGeneratorService.Infrastructure.Migrations
{
    [DbContext(typeof(DiscountDbContext))]
    partial class DiscountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("DiscountCodeGeneratorService.Domain.Entities.DiscountCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiscountCodes");
                });

            modelBuilder.Entity("DiscountCodeGeneratorService.Domain.Entities.DiscountCode", b =>
                {
                    b.OwnsOne("DiscountCodeGeneratorService.Domain.ValueObjects.DiscountUsageInfo", "UsageInfo", b1 =>
                        {
                            b1.Property<Guid>("DiscountCodeId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsUsed")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime?>("UsedTime")
                                .HasColumnType("TEXT");

                            b1.HasKey("DiscountCodeId");

                            b1.ToTable("DiscountCodes");

                            b1.WithOwner()
                                .HasForeignKey("DiscountCodeId");
                        });

                    b.Navigation("UsageInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
